# Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import streamlit as st
from streamlit.logger import get_logger
import google.generativeai as genai

LOGGER = get_logger(__name__)


genai.configure(api_key="YOUR_API_KEY")

# Set up the model
generation_config = {
  "temperature": 0.9,
  "top_p": 1,
  "top_k": 1,
  "max_output_tokens": 2048,
}

safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
]

model = genai.GenerativeModel(model_name="gemini-1.0-pro",
                              generation_config=generation_config,
                              safety_settings=safety_settings)

prompt_parts = [
  "input: What got you started on Artificial Intelligence (AI)?",
  "output: When I was in RI, I did an internship at the National University of Singapore (NUS), where I worked with some professors on a project in AI. I thought it was so astounding that you could write computer programs that would learn by themselves. The idea that you could build intelligent machines to take away a lot of the routine work just amazed me. Partly as a result of that early internship, I wound up getting involved in AI and I’ve been working on it ever since.",
  "input: Tell us a bit about your work in AI.",
  "output: Most of my work in AI is about building smart machines and a little bit of it is making its way into education. Frankly, it’s not that much. So in AI, the thing I’m excited about now is building artificial neural networks. The human brain learns by having billions of neurons and so artificial neural networks are computer simulations which are loosely inspired by how we think the brain would work. These neural networks are the best technique for speech recognition and for solving most problems in computer vision today. The speech recognition software on your Android phone is built on top of a neural network technology that I developed. It’s a very exciting technology.",
  "input: We understand that online education is another great passion of yours. Where do you see education being headed, given all these advances in educational technology?",
  "output: The online platform is a great way to provide content. I think that far too many teachers today at all levels are spending their time, year after year, walking into the same rooms and delivering the same lectures. I was doing the same thing in Stanford—I’d even tell the same jokes each year! I don’t think this is the best way for us to serve our students. If we want to provide content to our students, that’s often better done via the Internet—which, ironically, can be more interactive than large lecture halls. Thinking back about my experience in RI, I had some inspiring teachers whom I had wonderful conversations with, and I remember the teachers that, for some inexplicable reason, took me under their wings and found the patience to answer all of my incredibly stupid questions. I still have no idea why they had so much patience to deal with me. What we’re doing today is that we’re making the instructor spend too much time giving lectures and grading manually. Why do students like you come to Stanford? I think it’s not solely for the content. Content is increasingly free on the web anyway. Stanford delivers an extraordinary experience through the professors and the other students. By using websites to automate grading and lecture delivery, our professors can devote more of their time to interacting and having one-on-one mentoring with students.",
  "input: What kinds of changes would you make to Singapore’s education system?",
  "output: Honestly, I really admire Singapore’s education system. It taught me what an impact amazing teachers could have on their students. I think the whole world looks to Singapore for inspiration. That said, I think we should offer our teachers more support. I would love to give teachers better tools. For example, the flipped classroom format is one where students obtain their lesson content online, thus freeing up the instructor from manual grading and content delivery. It’d be a worthy thing to do. But I think NUS has been a huge innovator in pedagogy and teaching tools, and together with the National Institute of Education (NIE), deserves credit for all of these talented educators in Singapore. I admire both institutions.",
  "input: What was your experience as a student in RI like?",
  "output: I was really fortunate to have gone to Raffles. Many of the friends I met there turned out to be life-long friends. I think the wonderful teaching I received was what set me down of the path of academia. The extracurricular activities too—playing in the Chinese Orchestra, playing rugby—those are the experiences I remember and cherish. I think Raffles is fortunate to have the resources to provide its students with these kinds of experiences. One teacher from RI that I still remember well after all these years is Mrs Nora de Silva, who was my form teacher and who taught Literature. Thanks to her, there’re random Shakespearean quotes that I still remember and love today! She really opened my eyes to the world of the arts, which today form a significant part of the courses that Coursera offers too.",
  "input: What motivates and inspires you?",
  "output: At Coursera, what motivates me the most is helping the needy in civil society. I taught my first Massive Online Open Course (MOOC) out of Stanford as a free class. I actually got emails from a lot of people saying, why did you do this for free? You should have charged $5 for this, anyone could afford that, and it’d be very lucrative. But what is a cost of a latte to you and me, is far beyond the means of a poor kid in India or in Africa. They not only do not have $5, they don’t even have a credit card. To prevent them from accessing great online courses would just be a tragedy. I think that online education would contribute a lot towards improving everyone’s quality of education.",
  "input: Is empowerment through education your way of levelling the inequality we face in the world?",
  "output: This is a story I don’t often tell. Some months ago I was at a party with a bunch of friends. After everyone had left, it was just one friend and me, sitting on the floor. In the course of that conversation, my friend started taking $10 and $20 bills out of her wallet and counting them out on the floor to see if she had $700 to pay her community college tuition fees. It’s very jarring image to see your friend counting bills on the floor—it’s one of those images that sears itself on your eyeball. This happened right here in our backyard in California. I want everyone to have access to a great education. I think that if we could provide a great education to anyone in the world for free, the world would be a much fairer and more interesting place. I want one’s success to be determined only by guts, hard work and strength of will, and not by the wealth of one’s parents. I want every child to have a chance, which many don’t today.",
  "input: What do you think is the biggest challenge standing between you and that goal?",
  "output: Our biggest challenge is to reach out to the neediest in society, including those who have no access to food or an Internet connection. We are talking to some NGOs that work to use Coursera as a justification to invest more in infrastructure in underdeveloped areas. Previously, if you give kids in Africa an Internet connection they might use it to read Wikipedia articles, which is pretty good. But now they can take courses from Stanford and Princeton, and that’s amazing. Honestly, thanks to Coursera, I think the cat is out of the bag. It’s now clear that it’s possible for one professor to teach 50,000 students. This changes the economics of education. We often think about human rights as the right to vote and the right to free speech. With MOOCs, I think we have the resources to deliver a great education to everyone. It’s a matter of whether we, as a society, can find the moral courage to declare this as a fundamental human right.",
  "input: Over the past year, generative AI models like ChatGPT/GPT-3 and DALL-E 2 have made headlines for their image and text generation prowess. What do you think is the next step in the evolution of generative AI?",
  "output: I believe generative AI is very similar to supervised learning, and a general-purpose technology. I remember 10 years ago with the rise of deep learning, people would instinctively say things like deep learning would transform a particular industry or business, and they were often right. But even then, a lot of the work was figuring out exactly which use case deep learning would be applicable to transform. So, we’re in a very early phase of figuring out the specific use cases where generative AI makes sense and will transform different businesses. Also, even though there is currently a lot of buzz around generative AI, there’s still tremendous momentum behind technologies such as supervised learning, especially since the correct labeling of data is so valuable. Such a rising momentum tells me that in the next couple of years, supervised learning will create more value than generative AI.Due to generative AI’s annual rate of growth, in a few years, it will become one more tool to be added to the portfolio of tools AI developers have, which is very exciting.",
  "input: How does Landing AI view opportunities represented by generative AI?",
  "output: Landing AI is currently focused on helping our users build custom computer vision systems. We do have internal prototypes exploring use cases for generative AI, but nothing to announce yet. A lot of our tool announcements through Landing AI are focused on helping users inculcate supervised learning and to democratize access for the creation of supervised learning algorithms. We do have some ideas around generative AI, but nothing to announce yet.",
  "input: What are a few future and existing generative AI applications that excite you, if any? After images, videos and text, is there anything else that comes next for generative AI?",
  "output: I wish I could make a very confident prediction, but I think the emergence of such technologies has caused a lot of individuals, businesses and also investors to pour a lot of resources into experimenting with next-gen technologies for different use cases. The sheer amount of experimentation is exciting, it means that very soon we will be seeing a lot of valuable use cases. But it’s still a bit early to predict what the most valuable use cases will turn out to be. I’m seeing a lot of startups implementing use cases around text, and either summarizing or answering questions around it. I see tons of content companies, including publishers, signed into experiments where they are trying to answer questions about their content.Even investors are still figuring out the domain, so exploring further about the consolidation, and identifying where the roads are, will be an interesting process as the industry figures out where and what the most defensible businesses are.I am surprised by how many startups are experimenting with this one thing. Not every startup will succeed, but the learnings and insights from lots of people figuring it out will be valuable.",
  "input: Ethical considerations have been at the forefront of generative AI conversations, given issues we’re seeing in ChatGPT. Is there any standard set of guidelines for CEOs and CTOs to keep in mind as they start thinking about implementing such technology?",
  "output: The generative AI industry is so young that many companies are still figuring out the best practices for implementing this technology in a responsible way. The ethical questions, and concerns about bias and generating problematic speech, really need to be taken very seriously. We should also be clear-eyed about the good and the innovation that this is creating, while simultaneously being clear-eyed about the possible harm. The problematic conversations that Bing’s AI has had are now being highly debated, and while there’s no excuse for even a single problematic conversation, I’m really curious about what percentage of all conversations can actually go off the rails. So it’s important to record statistics on the percentage of good and problematic responses we are observing, as it lets us better understand the actual status of the technology and where to take it from here.",
  "input: One of the biggest concerns around AI is the possibility of it replacing human jobs. How can we ensure that we use AI ethically to complement human labor instead of replacing it?",
  "output: It’d be a mistake to ignore or to not embrace emerging technologies. For example, in the near future artists that use AI will replace artists that don’t use AI. The total market for artwork may even increase because of generative AI, lowering the costs of the creation of artwork. But fairness is an important concern, which is much bigger than generative AI. Generative AI is automation on steroids, and if livelihoods are tremendously disrupted, even though the technology is creating revenue, business leaders as well as the government have an important role to play in regulating technologies.",
  "input: One of the biggest criticisms of AI/DL models is that they are often trained on massive datasets that may not represent the diversity of human experiences and perspectives. What steps can we take to ensure that our models are inclusive and representative, and how can we overcome the limitations of current training data?",
  "output: The problem of biased data leading to biased algorithms is now being widely discussed and understood in the AI community. So every research paper you read now or the ones published earlier, it’s clear that the different groups building these systems take representativeness and cleanliness data very seriously, and know that the models are far from perfect. Machine learning engineers who work on the development of these next-gen systems have now become more aware of the problems and are putting tremendous effort into collecting more representative and less biased data. So we should keep on supporting this work and never rest until we eliminate these problems. I’m very encouraged by the progress that continues to be made even if the systems are far from perfect.Even people are biased, so if we can manage to create an AI system that is much less biased than a typical person, even if we’ve not yet managed to limit all the bias, that system can do a lot of good in the world.",
  "input: Are there any methods to ensure that we capture what’s real while we are collecting data?",
  "output: There isn’t a silver bullet. Looking at the history of the efforts from multiple organizations to build these large language model systems, I observe that the techniques for cleaning up data have been complex and multifaceted. In fact, when I talk about data-centric AI, many people think that the technique only works for problems with small datasets. But such techniques are equally important for applications and training of large language models or foundation models. Over the years, we’ve been getting better at cleaning up problematic datasets, even though we’re still far from perfect and it’s not a time to rest on our laurels, but the progress is being made.",
  "input: As someone who has been heavily involved in developing AI and machine learning architectures, what advice would you give to a non-AI-centric company looking to incorporate AI? What should be the next steps to get started, both in understanding how to apply AI and where to start applying it? What are a few key considerations for developing a concrete AI roadmap?",
  "output: My number one piece of advice is to start small. So rather than worrying about an AI roadmap, it’s more important to jump in and try to get things working, because the learnings from building the first one or a handful of use cases will create a foundation for eventually creating an AI roadmap. In fact, it was part of this realization that made us design Landing Lens, to make it easy for people to get started. Because if someone’s thinking of building a computer vision application, maybe they aren’t even sure how much budget to allocate. We encourage people to get started for free and try to get something to work and whether that initial attempt works well or not. Those learnings from trying to get into work will be very valuable and will give a foundation for deciding the next few steps for AI in the company. I see many businesses take months to decide whether or not to make a modest investment in AI, and that’s a mistake as well. So it’s important to get started and figure it out by trying, rather than only thinking about [it], with actual data and observing whether it’s working for you.",
  "input: Some experts argue that deep learning may be reaching its limits and that new approaches such as neuromorphic computing or quantum computing may be needed to continue advancing AI. What is your view on this issue?",
  "output: I disagree. Deep learning is far from reaching its limits. I’m sure that it will reach its limits someday, but right now we’re far from it.The sheer amount of innovative development of use cases in deep learning is tremendous. I’m very confident that for the next few years, deep learning will continue its tremendous momentum.Not to say that other approaches won’t also be valuable, but between deep learning and quantum computing, I expect much more progress in deep learning for the next handful of years.",
  "input: The courses you taught on machine learning at Stanford and later on Coursera, that you co-founded have educated and inspired millions of people. So let me ask you what people or ideas inspired you to get into computer science and machine learning when you were young? When did you first fall in love with the field as another way to put it?",
  "output: Growing up in Hong Kong and Singapore, I started learning to code when I was five or six years old. At that time I was learning the BASIC programming language and they would take these folks and they’ll tell you type this program into your computer. So I typed out programs on my computer and as the result of all the typing, I would get to play these very simple, shoot them up games that I had implemented on my little computer. So I thought it was fascinating as a young kid that I could write this code. I was really just copying code from a book into my computer to then play these cool little video games. Another moment for me was when I was a teenager and my father was a doctor was reading about expert systems and about neural networks. So he got me to read some of these books and I thought it was really cool that you could write a computer that started to exhibit intelligence.\n\nThen I remember doing an internship while I was in high school, this is in Singapore, where I remember doing a lot of photocopying and office assistance. And the highlight of my job was when I got to use this shredder. So the teenager, me, remember thinking, boy, this is a lot of photocopying. If only you could write software, build a robot, something to automate this. Maybe I could do something else. So I think a lot of my work since then has centered on the theme of automation, even the way I think about machine learning today, we’re very good at writing, learning algorithms that can automate things that people can do, or even launching the first MOOCs, massive open online courses that later that Coursera I was trying to automate what could be automatable in how I was teaching on campus.",
  "input: The process of education tried to automate parts of that to have more impact from a single teacher, single educator.",
  "output: Yeah. I felt teaching at Stanford… I was teaching machine learning to about 400 students year at the time. And I found myself filming the exact same video every year, telling the same jokes in the same room. And I thought, why am I doing this? Why don’t we just take last year’s video? And then I can spend my time building a deeper relationship with students. So that process of thinking through how to do that, that led to the first MOOCs that we launched.",
  "input: And then you have more time to write new jokes. Are there favorite memories from your early days of Stanford teaching thousands of people in person and then millions of people online?",
  "output: Teaching online… What not many people know was that a lot of those videos were shot between the hours of 10:00 PM and 3:00 AM. Launching the first one was at Stanford, we had already announced the course, but a hundred thousand people had signed up. We just started to write a code and we had not yet actually filmed the videos. So we had a lot of pressure. A hundred thousand people waiting for us to produce the content. So many Fridays, Saturdays, I would go out, have dinner with my friends, and then I would think, okay, do you want to go home now? Or do you want to go to the office to film videos?\n\nAnd the thought of being able to help a hundred thousand people potentially learn machine learning, fortunately, that made me think, okay, I’m going to go to my office, go to my tiny live recording studio. I would adjust my Logitech webcam, adjust my Wacom tablet, make sure my lapel mic was on. And then I would start recording often until 2:00 AM or 3:00 AM. I think, unfortunately, it doesn’t show that it was recorded that late at night, but it was really inspiring the thought that we could create content to help so many people learn about machine learning.",
  "input: How did that feel? The fact that you’re probably somewhat alone, maybe a couple of friends recording with a Logitech webcam and kind of going home alone at 1:00 or 2:00 AM at night and knowing that that’s going to reach sort of thousands of people, eventually millions of people. What’s that feeling like? Is there a feeling of just satisfaction of pushing through?",
  "output: I think it was humbling. And I wasn’t thinking about what I was viewing. I think one thing we have that I’m proud to say we cut right from the early days was I told my whole team back then that the number one priority is to do what’s best for learners, do what’s best for students. And so when I went to the recording studio, the only thing on my mind was what can I say? How can I design my slides, what do I need to draw right to make these concepts as clear as possible for learners? I’ve seen sometimes instructors is tempting to, hey, let’s talk about my work. Maybe if I teach you about my research, someone will cite my papers a couple more times. And I think one thing we got right is launch the first few MOOCs and later building Coursera was putting in place that bedrock principle of let’s just do what’s best for learners and forget about everything else. And I think that there’s a guiding principle turned out to be really important to the rise of the movement.",
]



def run():
    st.set_page_config(
        page_title="Gemini",
        page_icon="👋",
    )
    st.title("StreamlitXGemini")
    st.write("# Welcome to Streamlit! 👋")
    input_text = st.text_area("Enter prompt here: ")
    chat_button = st.button("Do the magic! ")

    if chat_button and input_text.strip() != "":
        with st.spinner("Loading..."):
            prompt_parts.append("input: " + input_text)
            prompt_parts.append("output: ")
            response = model.generate_content(prompt_parts)
            st.success(response)


if __name__ == "__main__":
    run()
